version: "3"

services:
    backup:
        image: "ghcr.io/jensostertag/mysql-backup:latest"
        restart: "always"
        environment:
            TZ: "Europe/Berlin"
            DB_HOST: "localhost"
            DB_USER: "root"
            DB_PASS: "root"
            DB_DATABASE: "database"
        volumes:
            - "./backup:/backup"
