name: "Push to main branch"

on:
    push:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"

            - name: "Login to GitHub Container Registry"
              uses: "docker/login-action@v3"
              with:
                  registry: "ghcr.io"
                  username: "${{ github.actor }}"
                  password: "${{ secrets.GITHUB_TOKEN }}"

            - name: "Get lowercase repository details"
              id: "lowercase-repo-details"
              run: |
                  echo "REPOSITORYLC=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

            - name: "Docker Buildx setup"
              uses: "docker/setup-buildx-action@v3"

            - name: "Build and push image"
              uses: "docker/build-push-action@v5"
              with:
                  context: "."
                  push: "true"
                  tags: "ghcr.io/${{ env.REPOSITORYLC }}:latest"
                  cache-from: "type=gha"
                  cache-to: "type=gha,mode=max"
